### ISSUE TITLE
Sanitize our inputs

### ISSUE THREAD

**Issue by davidmelvin** [JoshuaStorm/meetable#140]
defensive programming so we don't blow stuff up
part of this is client side (this is a negative number)
part of server side (this isn't an email we have in our database? I don't know any actual examples)

we can't schedule 0.5 hour long meetings

- [ ] what if start and end times are equal or backwards
- [ ] meeting duration is longer than window start - window end

**Comment by JoshuaStorm** [comment]
I guess this I'll do this on the backend now with Meteor's built in `check` that is missing on a few functions
