### ISSUE TITLE
change color scheme

### ISSUE THREAD

**Issue by davidmelvin** [JoshuaStorm/meetable#226]
I think we should change the default [color scheme](https://github.com/FezVrasta/bootstrap-material-design#colors). 

Any suggestions? We need to choose 5 colors to fill the Boostrap color palette. this is low priority, i just want to make the ui look bomb you know.

Keep in mind the main color that the user sees is called "primary" and it is currently the greenish color we have.

One of my ideas: https://coolors.co/446cb3-86bbd8-758e4f-f6ae2d-f26419
-  Primary: SAN MARINO 446CB3 68,108,179
- map the success, info, warning, danger to the appropriate colors

We can choose colors from http://www.flatuicolorpicker.com and https://coolors.co

**Comment by davidmelvin** [comment]
change primary color to new meetable blue

**Comment by JoshuaStorm** [comment]
Closed by #292
